version: '3'
services:
  bd:
    image: postgres:13.4-alpine
    container_name: TeamTCJ_BD_postgres_v13.4
    volumes:
      - teamtcj_postgres_data:/var/lib/postgresql/data    
    environment:
      - POSTGRES_DB=teamtcj
      - POSTGRES_USER=teamtcj
      - POSTGRES_PASSWORD=yC@^QPohK@ak
      - DEBIAN_FRONTEND=noninteractive
      - TZ=America/Bogota
      - PGTZ='GMT-5'
    restart: always 
    ports:
      - 5435:5432
  web:
    build: .
    image: "teamtcj:v1.0"    
    container_name: teamtcj_app_v1.0
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - TZ=America/Bogota
    volumes:
      - ./app/:/app
    restart: always
    depends_on: 
      - bd
volumes:
  teamtcj_postgres_data: